from datetime import datetime, timedelta, timezone
from dateutil.parser import parse
import pytz





def get_dates_to_end_of_month(interval_minutes=30, tz=pytz.timezone('Europe/Bratislava')):
        """
        Generate a list of datetime objects from now until the end of the current month in specified intervals.

        interval_minutes: The interval in minutes. Default is 30.
        A list of datetime objects.
        """
        now = datetime.now(tz).replace(microsecond=0)
        # Calculate the start of the next month
        next_month = (now.month % 12) + 1
        year = now.year + (1 if next_month == 1 else 0)
        start_of_next_month = datetime(year, next_month, 1)

        # Generate the list of dates
        dates = []
        current_time = now
        while current_time < start_of_next_month:
            dates.append(current_time)
            current_time += timedelta(minutes=interval_minutes)

        return dates

def filter_dates(rm_dates):
        """
        Remove dates from the list generated by get_dates_to_end_of_month that fall within specified ranges.

        :param rm_dates: A list of tuples with start and end datetime objects, e.g., [(datetime_from, datetime_to)].
        :return: A filtered list of datetime objects.
        """
        data_list = get_dates_to_end_of_month()
        for start_date, end_date in rm_dates:
            data_list = [date for date in data_list if not (start_date <= date <= end_date)]
        return data_list